spring:
  data:
    redis:
      port: 6379
      password:
      host: localhost

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 106642161039-utb59dmeun2m63rqchh1bs661chu10q4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            client-id: 5EtyOfkLapGdvHgNMIE8
            client-secret: WFFRLIng4T
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: nickname , email , profile_image , gender, age  # 동의 항목
            client-name: Naver
          kakao:
            client-id: 6ea3ac3c0fe9c2a77b274dec288988c6
            client-secret: xaPcMd2TpDJFbPBqEc2aeWxJCAe6eUyS
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/yeogi

jwt:
  secret-key : 6ae381eece6e5be0fcb4559dc952e1b95aa80d33d00d6078bb348c1fa9820498