spring:
  data:
    redis:
      port: 6379
      password:
      host: localhost
  datasource:
    h2:
      console:
        enabled : true
        path: /h2-console
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
