name: Assign Random Reviewer

on:
  pull_request:
    branches:
      - "develop"

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Select Random Reviewer
        id: select-reviewer
        run: |
          pr_author=${{ github.event.pull_request.user.login }}
          reviewers=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contributors | jq -r '.[].login')
          reviewer_array=($reviewers)
          filtered_reviewers=()
          
          for reviewer in "${reviewer_array[@]}"; do
            if [ "$reviewer" != "$pr_author" ]; then
              filtered_reviewers+=("$reviewer")
            fi
          done
          
          random_index=$(($RANDOM % ${#filtered_reviewers[@]}))
          selected_reviewer=${filtered_reviewers[$random_index]}
          echo "Selected reviewer: $selected_reviewer"
          echo "::set-output name=reviewer::$selected_reviewer"

      - name: Map Reviewer to Discord ID
        id: map-reviewer
        run: |
          selected_reviewer=${{ steps.select-reviewer.outputs.reviewer }}
          case "$selected_reviewer" in
            "Kwonnamhyung") discord_id='<@1028195605954183218>' ;;
            "Yejun4911") discord_id='<@347345984688488459>' ;;
            "ca1af") discord_id='<@345992113109991434>' ;;
            *) discord_id="$selected_reviewer" ;;
          esac
          echo "Discord ID: $discord_id"
          echo "::set-output name=discord_id::$discord_id"

      - name: Add reviewer to PR
        run: |
          pr_number=${{ github.event.pull_request.number }}
          reviewer=${{ steps.select-reviewer.outputs.reviewer }}
          curl -s -X POST -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" -d '{"reviewers":["'"$reviewer"'"]}' "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/requested_reviewers"

      - name: Send Discord Notification
        run: |
          webhook_url=${{ secrets.DISCORD_WEBHOOK_URL }}
          discord_id=${{ steps.map-reviewer.outputs.discord_id }}
          pr_number=${{ github.event.pull_request.number }}
          pr_title=${{ github.event.pull_request.title }}
          pr_url=${{ github.event.pull_request.html_url }}
          
          payload=$(cat <<EOF
          {
            "content": "새로운 PR이 생성되었습니다. [#$pr_number] \n $discord_id 님, 아래 URL에서 PR을 리뷰 해 주세요!\n$pr_url"
          }
          EOF
          )

          curl -X POST -H "Content-Type: application/json" -d "$payload" $webhook_url
